require 'nanoc3/tasks'

desc "Compiles the static site contents using nanoc"
task :compile do |t|
    sh "nanoc compile"
end

task :default => [:compile]

desc "Builds and deploys to goosoftware.co.uk"
task :deploy => [:compile, 'deploy:rsync']